# Generated by Django 2.1.7 on 2019-02-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='audiopath',
            field=models.CharField(default='audiopath', max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='images',
            field=models.CharField(default='images', max_length=500),
        ),
        migrations.AddField(
            model_name='meeting',
            name='imagespath',
            field=models.CharField(default='imagespath', max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.CharField(default='time', max_length=10),
        ),
        migrations.AddField(
            model_name='meeting',
            name='transcript',
            field=models.CharField(default='transcript', max_length=1000),
        ),
        migrations.AddField(
            model_name='meeting',
            name='words',
            field=models.CharField(default='words', max_length=1000),
        ),
    ]
