# Generated by Django 2.1.7 on 2019-02-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20190218_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='time',
            new_name='tim',
        ),
    ]
