# Generated by Django 2.1.7 on 2019-02-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20190218_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='audiopath',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='images',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='imagespath',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meetingpath',
            field=models.CharField(default='meetingpath', max_length=100),
        ),
    ]
