# Generated by Django 2.1.7 on 2019-02-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20190218_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meetingpath',
        ),
    ]
